### ISSUE TITLE
Missing requirements for zmq in DEPENDENCIES.md

### ISSUE THREAD

**Issue by nadahalli** [talaia-labs/python-teos#110]
apt-get install python3-dev
pip3 install wheel

Adding both of these helped.

**Comment by sr-gi** [comment]
What distro a Python version where you using?

**Comment by nadahalli** [comment]
tejaswi@rubble:~$ python3 --version
Python 3.6.9

**Comment by sr-gi** [comment]
And I'm guessing you're using an Ubuntu-based distro given that you mentioned `apt-get install`.

Did `pip` throw any error on getting `zmq` due to not having `python3-dev` and `wheel`? Could you provide them?

I've installed it myself in Ubuntu without facing this. It may be the case that they where already there.

**Comment by nadahalli** [comment]
tejaswi@rubble:~/sandbox/python-teos$ pip3 install -r requirements.txt
Collecting zmq (from -r requirements.txt (line 1))
  Downloading
https://files.pythonhosted.org/packages/6e/78/833b2808793c1619835edb1a4e17a023d5d625f4f97ff25ffff986d1f472/zmq-0.0.0.tar.gz
Collecting flask (from -r requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl
(94kB)
    100% |████████████████████████████████| 102kB 2.2MB/s
Collecting cryptography==2.8 (from -r requirements.txt (line 3))
  Downloading
https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl
(2.3MB)
    100% |████████████████████████████████| 2.3MB 709kB/s
Collecting coincurve (from -r requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/e8/3c/0278772998e905d02ad7bb15a49d3749d02fa13c49dabb6c298adadcf1d4/coincurve-13.0.0-cp36-cp36m-manylinux1_x86_64.whl
(527kB)
    100% |████████████████████████████████| 532kB 2.3MB/s
Collecting pyzbase32 (from -r requirements.txt (line 5))
  Downloading
https://files.pythonhosted.org/packages/4c/f5/a620d82acced80ed3a5fd870caafcc33b85a3fe4ca6599a42001bb5a741c/pyzbase32-0.0.1.tar.gz
Collecting requests (from -r requirements.txt (line 6))
  Cache entry deserialization failed, entry ignored
  Downloading
https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
(58kB)
    100% |████████████████████████████████| 61kB 9.9MB/s
Collecting plyvel (from -r requirements.txt (line 7))
  Downloading
https://files.pythonhosted.org/packages/7a/86/a54fd9cdb6740fcb0655528d55254fed6459df2464272b484164d999451a/plyvel-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
(617kB)
    100% |████████████████████████████████| 624kB 1.7MB/s
Collecting pyzmq (from zmq->-r requirements.txt (line 1))
  Downloading
https://files.pythonhosted.org/packages/41/fa/e6e10410f01b03d10ab0705717d1246f63cdbbc0676140c78f0f757db332/pyzmq-19.0.0-cp36-cp36m-manylinux1_x86_64.whl
(1.1MB)
    100% |████████████████████████████████| 1.1MB 1.3MB/s
Collecting itsdangerous>=0.24 (from flask->-r requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from flask->-r requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl
(126kB)
    100% |████████████████████████████████| 133kB 7.8MB/s
Collecting click>=5.1 (from flask->-r requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl
(82kB)
    100% |████████████████████████████████| 92kB 11.9MB/s
Collecting Werkzeug>=0.15 (from flask->-r requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/ba/a5/d6f8a6e71f15364d35678a4ec8a0186f980b3bd2545f40ad51dd26a87fb1/Werkzeug-1.0.0-py2.py3-none-any.whl
(298kB)
    100% |████████████████████████████████| 307kB 3.6MB/s
Collecting cffi!=1.11.3,>=1.8 (from cryptography==2.8->-r requirements.txt
(line 3))
  Downloading
https://files.pythonhosted.org/packages/f1/c7/72abda280893609e1ddfff90f8064568bd8bcb2c1770a9d5bb5edb2d1fea/cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
(399kB)
    100% |████████████████████████████████| 399kB 3.8MB/s
Collecting six>=1.4.1 (from cryptography==2.8->-r requirements.txt (line 3))
  Cache entry deserialization failed, entry ignored
  Downloading
https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting asn1crypto (from coincurve->-r requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/e9/51/1db4a60049fb7390959be586b6eb743098e6cea3f6b2d3ed9e17fec62ba2/asn1crypto-1.3.0-py2.py3-none-any.whl
(103kB)
    100% |████████████████████████████████| 112kB 8.5MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r
requirements.txt (line 6))
  Cache entry deserialization failed, entry ignored
  Downloading
https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
(125kB)
    100% |████████████████████████████████| 133kB 10.7MB/s
Collecting idna<3,>=2.5 (from requests->-r requirements.txt (line 6))
  Cache entry deserialization failed, entry ignored
  Downloading
https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
(58kB)
    100% |████████████████████████████████| 61kB 8.8MB/s
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 6))
  Cache entry deserialization failed, entry ignored
  Downloading
https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
(156kB)
    100% |████████████████████████████████| 163kB 6.3MB/s
Collecting chardet<4,>=3.0.2 (from requests->-r requirements.txt (line 6))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading
https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
(133kB)
    100% |████████████████████████████████| 143kB 5.1MB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask->-r
requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography==2.8->-r
requirements.txt (line 3))
  Downloading
https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
(112kB)
    100% |████████████████████████████████| 112kB 6.2MB/s
Building wheels for collected packages: zmq, pyzbase32
  Running setup.py bdist_wheel for zmq ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-pqt4i1b5/zmq/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
/tmp/tmpun4ghda3pip-wheel- --python-tag cp36:
  You probably meant 'pyzmq' not 'zmq'
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for zmq
  Running setup.py clean for zmq
  Running setup.py bdist_wheel for pyzbase32 ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-pqt4i1b5/pyzbase32/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
/tmp/tmpsz6pv19dpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pyzbase32
  Running setup.py clean for pyzbase32
Failed to build zmq pyzbase32
Installing collected packages: pyzmq, zmq, itsdangerous, MarkupSafe,
Jinja2, click, Werkzeug, flask, pycparser, cffi, six, cryptography,
asn1crypto, coincurve, pyzbase32, urllib3, idna, certifi, chardet,
requests, plyvel
  Running setup.py install for zmq ... done
  Running setup.py install for pyzbase32 ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-pqt4i1b5/pyzbase32/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/tmp/pip-3itz3kc7-record/install-record.txt
--single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pyzbase32
    copying pyzbase32/__init__.py -> build/lib.linux-x86_64-3.6/pyzbase32
    copying pyzbase32/__main__.py -> build/lib.linux-x86_64-3.6/pyzbase32
    running build_ext
    building 'pyzbase32.ext' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -fPIC -Iinclude -I/usr/include/python3.6m -c
src/pyzbase32.c -o build/temp.linux-x86_64-3.6/src/pyzbase32.o
    src/pyzbase32.c:1:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-pqt4i1b5/pyzbase32/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/tmp/pip-3itz3kc7-record/install-record.txt
--single-version-externally-managed --compile --user --prefix=" failed with
error code 1 in /tmp/pip-build-pqt4i1b5/pyzbase32/

**Comment by sr-gi** [comment]
Great, I'll look into it.

**Comment by sr-gi** [comment]
I've been digging into this:

For `Ubuntu 18.04.4`, `Python 3.6.9` and `pip 9.0.1` seems to be no issue.

For what I can see on getting `pip 9.0.1`:

```
root@9eb8a5ed9e5d:/# apt-get install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  [...]
Suggested packages:
  [...]
The following NEW packages will be installed:
  [...] python-pip-whl [...] python3-wheel [..]  python3.6-dev [...]
```
So it may have been a pip version issue. Could you check what pip version do you have (if you didn't update it on the process)?

**Comment by nadahalli** [comment]
tejaswi@rubble:~/.bitcoin$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

I will setup a sandbox with your versions and see if I can replicate the
issue again.

**Comment by sr-gi** [comment]
Added `wheel` in https://github.com/talaia-labs/python-teos/commit/4181e4bcddc59d5243c28e2de28cb8ff89a5b5b4 since I've got it missing in some distros when working on https://github.com/talaia-labs/python-teos/pull/152.
