### ISSUE TITLE
ChaCha20Poly1305 is not supported by this version of OpenSSL

### ISSUE THREAD

**Issue by javiervargas** [talaia-labs/python-teos#116]
**Background**

Hi,   I'm running tower:

```
javier@bitcoin:~/python-teos$ python -m teos.teosd

24/03/2020 21:31:59 [Daemon]: Starting TEOS.
24/03/2020 21:31:59 [Daemon]: Fresh bootstrap.
24/03/2020 21:43:59 [ChainMonitor]: New block received via polling (block_hash=0000000000000000000c73e8a2077020b263eaa87f3241cc6ac8d3b0064dd066).
24/03/2020 21:43:59 [Responder]: New block received (block_hash=0000000000000000000c73e8a2077020b263eaa87f3241cc6ac8d3b0064dd066, prev_block_hash=000000000000000000068a93bde90329e9d19cc40fb232f6bbb356cab527bebe).
```
And when I try to send an appointment I get this error:

```
javier@bitcoin:~/python-teos$ python -m cli.teos_cli add_appointment -f dummy_appointment_data.json
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/javier/python-teos/cli/teos_cli.py", line 470, in <module>
    main(args, command_line_conf)
  File "/home/javier/python-teos/cli/teos_cli.py", line 405, in main
    add_appointment(args, teos_url, config)
  File "/home/javier/python-teos/cli/teos_cli.py", line 147, in add_appointment
    appointment_data["encrypted_blob"] = Cryptographer.encrypt(Blob(tx), tx_id)
  File "/home/javier/python-teos/common/cryptographer.py", line 129, in encrypt
    cipher = ChaCha20Poly1305(sk)
  File "/home/javier/.local/lib/python3.5/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 21, in __init__
    exceptions._Reasons.UNSUPPORTED_CIPHER
cryptography.exceptions.UnsupportedAlgorithm: ChaCha20Poly1305 is not supported by this version of OpenSSL
```

Checking openssl version:
```
javier@bitcoin:/usr/local/bin$ openssl
OpenSSL> version
OpenSSL 1.0.2g  1 Mar 2016
OpenSSL>
javier@bitcoin:~/python-teos$
```

I've updated to last version:

```
javier@bitcoin:~/python-teos$ openssl version
OpenSSL 1.1.1e  17 Mar 2020
javier@bitcoin:~/python-teos$ 
```

And I get the same error.

```
**Your enviroment**

Ubuntu 16.04
Bitcoind 0.18
Python Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
cryptography : Name: cryptography Version: 2.8
```

Thanks!
J.

**Comment by sr-gi** [comment]
The issue makes sense for a version of openssl prior to 1.1, since that's where ChaCha20 was added to it, but it's weird to have it for a recent version.

I'll update the install docs ([INSTALL.md](https://github.com/talaia-labs/python-teos/blob/master/INSTALL.md) and [cli/INSTALL.md](https://github.com/talaia-labs/python-teos/blob/master/cli/INSTALL.md)) to highlight that openssl 1.1 is required.

Can you reinstalling wiping cryptography and getting it again after upgrading openssl?

**Comment by javiervargas** [comment]
Done.

I've reinstalled cryptography and now it's working.

`javier@bitcoin:~/python-teos$ python -m cli.teos_cli add_appointment -f dummy_appointment_data.json
25/03/2020 13:37:32 [Client]: Sending appointment to the Eye of Satoshi.
25/03/2020 13:37:32 [Client]: Appointment accepted and signed by the Eye of Satoshi.
25/03/2020 13:37:32 [Client]: Appointment saved at /home/javier/.teos_cli/appointment_receipts/appointment-1585139852-0b9510d92a50c1d67c6f7fc5d47908d9-2aae0dcb432d4fae8c71c11aaae7a4db.json.
javier@bitcoin:~/python-teos$ 
`

Tower:
`25/03/2020 13:37:32 [DBManager]: Adding appointment to Watchers's db (uuid=eaad67b3c9c54188b125b9befdea23c1).
25/03/2020 13:37:32 [DBManager]: Locator not found in the db (locator=0b9510d92a50c1d67c6f7fc5d47908d9).
25/03/2020 13:37:32 [DBManager]: Creating new locator map (locator=0b9510d92a50c1d67c6f7fc5d47908d9, uuid=eaad67b3c9c54188b125b9befdea23c1).
25/03/2020 13:37:32 [Watcher]: New appointment accepted (locator=0b9510d92a50c1d67c6f7fc5d47908d9).
25/03/2020 13:37:32 [API]: Sending response and disconnecting (error=None, from_addr=127.0.0.1, response={'locator': '0b9510d92a50c1d67c6f7fc5d47908d9', 'signature': 'dhkkbpjq35uxm3msgrygr3gojri4qb8fahzhu9rprna9wpukze4qn9aygi7eajpij1z4gasm3nontc55iemjqappor8xwg7gmfe5q98g'}).`

However I got first error http 500 querying locator:

`25/03/2020 13:40:17 [API]: Received get_appointment request (locator=0b9510d92a50c1d67c6f7fc5d47908d9, from_addr=127.0.0.1).
[2020-03-25 13:40:17,908] ERROR in app: Exception on /get_appointment [GET]
Traceback (most recent call last):
  File "/home/javier/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/javier/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/javier/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/javier/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/javier/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/javier/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/javier/python-teos/teos/api.py", line 140, in get_appointment
    appointment_data = self.watcher.db_manager.load_watcher_appointment(uuid)
  File "/home/javier/python-teos/teos/db_manager.py", line 158, in load_watcher_appointment
    return self.load_entry(WATCHER_PREFIX + key)
  File "/home/javier/python-teos/teos/db_manager.py", line 129, in load_entry
    data = json.loads(data) if data is not None else data
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`

**Comment by sr-gi** [comment]
> Python Python 3.5.2
[...]
> TypeError: the JSON object must be str, not 'bytes'

This looks like a Python version issue. `json.loads` only accepts bytes as argument from Python 3.6 onwards.

https://docs.python.org/3/library/json.html#json.loads
https://docs.python.org/3.6/library/json.html#json.loads

I'd recommend either updating the Python version or installing 3.6 as a different binary.

Please do confirm if upgrading solves the issue and I'll add Python 3.6 as the minimal requirement to run the code.

**Comment by javiervargas** [comment]
I'll try to install 3.6,  meanwhile I've added a conversion str(data, encoding) and now it's working.
