### ISSUE TITLE
Dockerize teos

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/python-teos#125]
Create a docker image for `teos` so it is easier to install and distribute.

The task should include:

- a docker image for `teos`
- a step by step section on the [README](https://github.com/talaia-labs/python-teos/blob/master/README.md) on how to deploy and use `teos` using docker.

**Comment by aljazceru** [comment]
i'll tackle this

**Comment by RiccardoMasutti** [comment]
Would be awesome to see this in BTCPay @NicolasDorier @Kukks @rockstardev
