### ISSUE TITLE
Add automated multiarch docker builds and publish to docker hub

### ISSUE THREAD

**Issue by Kukks** [talaia-labs/python-teos#159]
Should be easy enough if you copy the following circleci config in your own and set up docker hub:
https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/.circleci/config.yml

**Comment by sr-gi** [comment]
Build for amd64, arm32 and arm64 are ready at https://hub.docker.com/repository/docker/talaia/python-teos/

I have a couple missing things to test regarding circle-ci, but it should be good to go.
