### ISSUE TITLE
Have separate data folders for mainnet, testnet and regtest

### ISSUE THREAD

**Issue by bigspider** [talaia-labs/python-teos#169]
Currently, the data folder for logs and appointments is the same (e.g. `~/.teos`) regardless of which network teos is running against. That creates a risk of running teos with the data folder of a different network than the intended one.

Mimicking bitcoind, it would be better to have different data folders for different network, by adding a suffix for non-mainnet networks. For example:

- ~/.teos contains teos.conf and is the data folder for mainnet
- ~/.teos/regtest is the data folder for regtest
- ~/.teos/testnet is the data folder for testnet
- similarly for signet, I guess

**Comment by sr-gi** [comment]
Don't bother about signet for now since there is no coverage atm.
