### ISSUE TITLE
Error running teosd: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by billygarrison** [talaia-labs/python-teos#257]
I received this error message when I ran `teosd` for the first time.

The solution was to upgrade protobuf (python package). Not sure if I already had an old version or if this is what `pip3 install -r requirements.txt` installed. The fix was:

```
pip uninstall protobuf python3-protobuf
pip install --upgrade pip
pip install --upgrade protobuf
```

Posting this here so if anyone runs into the same issue they can find the fix by searching issues.

Should DEPENDENCIES.md and/or requirements.txt be updated to include version of protobuf?

**Comment by sr-gi** [comment]
Hi Billy, thanks for the report.

Will check the minimal required version of protobuf and update `requirements.txt` accordingly.

Do you happen to know what version were you running initially?

**Comment by billygarrison** [comment]
I'm not sure which version, sorry.

**Comment by sr-gi** [comment]
`_internal_create_key` was added to `google.protobuf.descriptior` in https://github.com/protocolbuffers/protobuf/commit/6f129c123e02673736d8facd8dc046a38a4375b88, dating from 10th March.

The first release that covers that commit is 3.12.0, from 16th May (https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0), so I'm guessing that'd be our minimal required version. Can you confirm your current version is greater or equal to that?

**Comment by billygarrison** [comment]
My version is 3.14.0

**Comment by sr-gi** [comment]
OK, I was able to reproduce. 

**protobuf 3.11.3 (last 3.11 on PyPi)**

```
> python -m teos.teosd
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sergi/git/python-teos/teos/teosd.py", line 15, in <module>
    import teos.api as api
  File "/Users/sergi/git/python-teos/teos/api.py", line 13, in <module>
    from teos.protobuf.user_pb2 import RegisterRequest, GetSubscriptionInfoRequest
  File "/Users/sergi/git/python-teos/teos/protobuf/user_pb2.py", line 23, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**protobuf 3.12.0 runs correctly**
