### ISSUE TITLE
Appointments getting added for no apparent reason

### ISSUE THREAD

**Issue by billygarrison** [talaia-labs/python-teos#260]
I am running the c-lightning plugin (c-lightning v0.9.1), teos from master, bitcoind v0.20.1

Two things have caught my attention that I'm confused about. Not sure if there's an issue or I'm misunderstanding what's happening:

1. Appointments are getting added without channel balance updates (that I know of). `lightning-cli listforwards` doesn't show any new forwards. I haven't paid or received any invoice payments.

2. Appointments are getting added in groups of six. So far there have been two batches of six appointments that were added.

I will DM you a link to the output log (not sure if there's anything sensitive there)

**Comment by sr-gi** [comment]
Just saw the related c-lightning issue was closed.

For the record, the appointments belonged to fee updates in the commitment tx for ongoing channels. I will write down documentation on the cases were a commitment update can trigger so it's clearer in the future.

I'll close the issue if you have no objection.

**Comment by billygarrison** [comment]
Thanks @sr-gi!
