### ISSUE TITLE
Path eror running c-lightning plugin tests

### ISSUE THREAD

**Issue by orbitalturtle** [talaia-labs/python-teos#263]
When running pytest in watchtower-plugin I get the following error for a few of the tests:

`Warning: Skipping -wallet path that doesn't exist. Failed to load database path '/tmp/ltests-f54ew0ul/test_watchtower_misbehaving_1/regtest/"test"'. Path does not exist.`

Happy to investigate this... But thought I'd see if it's a familiar error or a sign I goofed up during setup

**Comment by sr-gi** [comment]
I'm taking a look to it, care to point out whats tests (also, Python version and pytest version and OS).

**Comment by sr-gi** [comment]
Can you take a look at https://github.com/talaia-labs/python-teos/pull/265?

The issue seems kinda unrelated, but there were some random issues with the plugin tests that may be relevant.

**Comment by orbitalturtle** [comment]
Awesome. Just tried that and the tests run fine now so I think that fixed it :D
