### ISSUE TITLE
teos quits without any output

### ISSUE THREAD

**Issue by svewa** [talaia-labs/python-teos#278]
Just installed teos using the pypy method.
.teos/teos.conf:
> [bitcoind]
> btcrpcuser=user
> btcrpcpassword=pass
> btcrpcconnect=10.44.0.62
> btcfeedconnect=10.44.0.62
> 
> [teos]
> max_appointments = 100000

    teos@s-teos:~$ ./.local/bin/teosd --overwritekey
    teos@s-teos:~$ ./.local/bin/teosd 
    teos@s-teos:~$ ./.local/bin/teosd -d
    Starting TEOS

neither of this leaves me with a running teos process, only output I could get is the "Starting TEOS" with `-d`.

**Comment by sr-gi** [comment]
That's pretty odd.

> teos@s-teos:\~$ ./.local/bin/teosd --overwritekey
> teos@s-teos:\~$ ./.local/bin/teosd 

This should output both in terminal and the logfile `(~/.teos/teos.log)`

> teos@s-teos:\~$ ./.local/bin/teosd -d
> Starting TEOS

This should be the expected behaviour though, since running in daemon mode should only log in the logfile.

Can you check if you're getting any output on the logfile? Furthermore, what distro, python version and teos version are you running so I can try to reproduce?

**Comment by svewa** [comment]
I'm running a debian 10 LXC unpriviledged container.
the call with `-d` might be expected behavior for the output, but afterwards there does not seem to be any process running. Logfile is equal to cli output, so in the `-d` case "Starting TEOS".

I installed pip3 and tried to install teos. This failed as some rust components did not build. So I updated pip3 `pip3 install --upgrade pip` after which the teos installation process ran without errors. This is when I opened the issue, as no persistent processes seemed to be invoked. Python is 3.7.3. Teos is from pypy and does not have a --version switch or similar, but it's possibly 0.1.1 as I have files like: 
> ./.local/lib/python3.7/site-packages/python_teos-0.1.1.dist-info

Then I noticed that `pip install --upgrade pip==9.0.3` is specifically mentioned in https://github.com/talaia-labs/python-teos/blob/master/DEPENDENCIES.md so I tried this, and it somehow botched my system. I have little clue about python, so I'll restart from scratch.

**Comment by svewa** [comment]
So I ran a few more tests today, each attempt from a freshly bootstrapped container.

##pip==9.0.3 seems broken
all attempts that involved the like `pip3 install --upgrade pip==9.0.3` stopped working at this very moment, is this version really required as mentioned in DEPENDENCIES.md?

## latest pip
So I just `pip3 --upgrade pip` to latest version and got some more success. Using pypy to install, 
`.teos/teos.conf`is in place, but had wrong format. While I fixed this meanwhile, I'm keeping this in, as it is still weird behavior:

executing `/usr/local/bin/teosd`sometimes does give output! other times not! So maybe when I opened the ticket I had just bad luck? All executions of teosd returned immediately.

    root@s-teos:.# /usr/local/bin/teosd
    09/04/2021 06:05:38 [Daemon] Tower identity found. Loading keys
    09/04/2021 06:05:38 [Daemon] ERROR: An error occurred: Cannot connect to bitcoind. Shutting down
    root@s-teos:.# /usr/local/bin/teosd
    root@s-teos:.# /usr/local/bin/teosd
    root@s-teos:.# /usr/local/bin/teosd
    09/04/2021 06:05:43 [Daemon] Tower identity found. Loading keys
    09/04/2021 06:05:43 [Daemon] ERROR: An error occurred: Cannot connect to bitcoind. Shutting down
    root@s-teos:.# /usr/local/bin/teosd
    root@s-teos:.# /usr/local/bin/teosd
    09/04/2021 06:05:55 [Daemon] Tower identity found. Loading keys
    09/04/2021 06:05:55 [Daemon] ERROR: An error occurred: Cannot connect to bitcoind. Shutting down

Okay, it didn't take the config file as I had it in the wrong format, fixed it, now I'm getting more output, but still no persistent process.

    root@s-teos:~# /usr/local/bin/teosd
    09/04/2021 07:07:36 [Daemon] Tower identity found. Loading keys
    09/04/2021 07:07:36 [Daemon] tower_id = XXX
    09/04/2021 07:07:36 [Daemon] Starting TEOS
    09/04/2021 07:07:36 [Daemon] Fresh bootstrap
    09/04/2021 07:07:36 [Daemon] Internal API initialized. Serving at localhost:50051
    root@s-teos:~# /usr/local/bin/teosd
    09/04/2021 07:07:40 [Daemon] Tower identity found. Loading keys
    09/04/2021 07:07:40 [Daemon] tower_id = XXX
    09/04/2021 07:07:40 [Daemon] Starting TEOS
    09/04/2021 07:07:40 [Daemon] Fresh bootstrap
    09/04/2021 07:07:40 [Daemon] Internal API initialized. Serving at localhost:50051
    root@s-teos:~#

always returning to the shell, leaving no process running and port 50051 closed.

**Comment by sr-gi** [comment]
>  is this version really required as mentioned in DEPENDENCIES.md?

Not really, that may be an MRV, since some distros used to come with a really old version of pip3. Getting the latest version should do. I'll ope a ticket and change that.

> root@s-teos:~# /usr/local/bin/teosd
09/04/2021 07:07:40 [Daemon] Tower identity found. Loading keys
09/04/2021 07:07:40 [Daemon] tower_id = XXX
09/04/2021 07:07:40 [Daemon] Starting TEOS
09/04/2021 07:07:40 [Daemon] Fresh bootstrap
09/04/2021 07:07:40 [Daemon] Internal API initialized. Serving at localhost:50051

This is way more promising. Can you check the logfile now, the loglevel is set to debug for the file so you may find more info there. 

I'm guessing is gonna have something to do with the http server, given the process stops just when the api is initialised, but without outputting anything regarding the server. Can you try to change the default `wsgi` (`--wsgi=waitress`)?

**Comment by sr-gi** [comment]
This will be the expected output btw:

`--wsgi=guicorn`
```
09/04/2021 08:18:13 [Daemon] Tower identity found. Loading keys
09/04/2021 08:18:13 [Daemon] tower_id = XXX
09/04/2021 08:18:13 [Daemon] Starting TEOS
09/04/2021 08:18:13 [Daemon] Fresh bootstrap
09/04/2021 08:18:13 [Daemon] Internal API initialized. Serving at localhost:50051
09/04/2021 08:18:14 [API] Starting gunicorn 20.0.4
09/04/2021 08:18:14 [API] Listening at: http://127.0.0.1:9814 (13157)
09/04/2021 08:18:14 [API] Using worker: sync
09/04/2021 08:18:14 [API] Booting worker with pid: 13161
09/04/2021 08:18:14 [RPC] Initialized. Serving at localhost:8814
09/04/2021 08:18:14 [API] Initialized. Serving at localhost:9814
```

`--wsgi=waitress`
```
09/04/2021 08:20:22 [Daemon] Tower identity found. Loading keys
09/04/2021 08:20:22 [Daemon] tower_id = XXX
09/04/2021 08:20:22 [Daemon] Starting TEOS
09/04/2021 08:20:22 [Daemon] Fresh bootstrap
09/04/2021 08:20:22 [Daemon] Internal API initialized. Serving at localhost:50051
09/04/2021 08:20:23 [API] Initialized. Serving at localhost:9814
09/04/2021 08:20:23 [API] Serving on http://127.0.0.1:9814
09/04/2021 08:20:23 [RPC] Initialized. Serving at localhost:8814
```

**Comment by svewa** [comment]
While `.teos/teos.log` is the same as the output of the command when run in foreground, `--wsgi=waitress` did the trick, it seems. So thanks for your help! Yet I get minor output differences between the pypy and git install:

git:

    09/04/2021 14:20:11 [Daemon] Tower identity found. Loading keys
    09/04/2021 14:20:11 [Daemon] tower_id = 03cde536c021410af47a63a985ff6e5a025446aa857b259c9328a56abe07b48f57
    09/04/2021 14:20:11 [Daemon] Starting TEOS
    09/04/2021 14:20:11 [Daemon] Fresh bootstrap
    09/04/2021 14:20:11 [Daemon] Internal API initialized. Serving at localhost:50051
    09/04/2021 14:20:12 [API] Initialized. Serving at localhost:9814
    09/04/2021 14:20:12 [API] Serving on http://127.0.0.1:9814
    09/04/2021 14:20:12 [RPC] Initialized. Serving at localhost:8814

pypy:

    09/04/2021 14:21:58 [Daemon] Tower identity found. Loading keys
    09/04/2021 14:21:58 [Daemon] tower_id = 03837424816e002c3b533fba271c8b77a35ad779d6bef7622d4001d1a83b39f51c
    09/04/2021 14:21:59 [Daemon] Starting TEOS
    09/04/2021 14:21:59 [Daemon] Fresh bootstrap
    09/04/2021 14:21:59 [Daemon] Internal API initialized. Serving at localhost:50051
    09/04/2021 14:21:59 [RPC] Initialized. Serving at localhost:8814
    09/04/2021 14:21:59 [API] Initialized. Serving at localhost:9814

Both versions keep running until I ctrl-c them, all three ports are connectable. Going to hook up my CL next.
So I guess I'm just going to use waitress, don't know the difference anyway.

As the initial problem is solved now, shall I close the ticket? Shall I open new ones for
* wrong config options are silently ignored
* often no output when bitcoind can't be connected
* --wsgi=gunicorn fails without error

**Comment by sr-gi** [comment]
Hey @svewa, sorry for the late response. I'm testing this now on an Ubuntu VM and having similar issues.

In my case looks like it's only a matter of the logging server not printing to STDOUT, but it may be related. I'll get to the root of this and then we can decide on tickets and updating code / docs.

**Comment by sr-gi** [comment]
@svewa looks like I found the root of the issue. It has nothing to do with the wsgi server, but the logging server quitting too quickly.

It does not happens in every run, hence why I was having some trouble debuting it. Furthermore, the issue only happened in a pretty specific code path, in this case the tower not being properly configured resulting in the code raising an exception during the bootstrapping phase. Most likely the RPC connection details  with bitcoind was wrong.

I'm guessing the issue actually resolved after fixing the config file, which also included changing the wgsi server.

Can you try #280 in a fresh container and see if it fixes it? I tried on my development env (OSX) and in a Ubuntu VM and it works in both (it did not in the latter before the patch).

**Comment by svewa** [comment]
@sr-gi I build and ran this, and getting the same result. Sometimes output and useful errors, as often just terminating without any output.

    7  git clone https://github.com/sr-gi/python-teos.git
    8  cd python-teos/
    9  git checkout remotes/origin/278-silent-teos
    10  git branch
    11  vim teos/logger.py
    12  pip3 install .
    13  /usr/local/bin/teosd
    14  /usr/local/bin/teosd
    15  /usr/local/bin/teosd

Only one of those `teosd` calls had proper errors/output. Pasting my command history as I don't really know what I'm doing with git. Checked a file to confirm that this has your patch applied.

If you have trouble reproducing this, I can provide you with a container, it's isolated anyway.

**Comment by sr-gi** [comment]
@svewa doubled checked and looks like you were right. Turns out depending on the OS the logging server may not even start if the code fails too early during bootstrap. I've addressed that in the last commit, would you mind trying it out again?

If it does fail, feel free to share the container.

**Comment by svewa** [comment]
could not reproduce the error, so I'd assume it's fixed. Thanks.
