### ISSUE TITLE
wrong config options are silently ignored (config file) or crash with traceback (cli arguments).

### ISSUE THREAD

**Issue by svewa** [talaia-labs/python-teos#283]
If wrong config options are given, users have a hard time figuring this out.

If it's a wrong switch when calling `teosd`, at least there is an indication with a proper error message in the end, but a confusing traceback before that: 

    # /usr/local/bin/teosd --btc_rpcuser=foobar
    Traceback (most recent call last):
      File "/usr/local/bin/teosd", line 8, in <module>
        sys.exit(run())
      File "/usr/local/lib/python3.7/dist-packages/teos/teosd.py", line 420, in run
        "help",
      File "/usr/lib/python3.7/getopt.py", line 93, in getopt
        opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
      File "/usr/lib/python3.7/getopt.py", line 157, in do_longs
        has_arg, opt = long_has_args(opt, longopts)
      File "/usr/lib/python3.7/getopt.py", line 174, in long_has_args
        raise GetoptError(_('option --%s not recognized') % opt, opt)
    getopt.GetoptError: option --btc_rpcuser not recognized

If nonexistent  parameters (typo, cli-style, ...) are in ~/.teos/teos.conf they are completely ignored instead terminating with an appropriate error.

Also having different parameters in cli and .conf is not really helpful.

**Comment by sr-gi** [comment]
> If nonexistent parameters (typo, cli-style, ...) are in ~/.teos/teos.conf they are completely ignored instead terminating with an appropriate error.

I'm working on a patch for this atm, I saw it while testing your previous issue.


> Also having different parameters in cli and .conf is not really helpful.

This is a more delicate matter, since it implies a bigger refactor. I do agree though that them being different does not help. I'll consider normalising them.

**Comment by sr-gi** [comment]
> If nonexistent parameters (typo, cli-style, ...) are in ~/.teos/teos.conf they are completely ignored instead terminating with an appropriate error.

Regarding this, is it not common practice to ignore them? I'm pretty certain that the same applies to `bitcoind` for unknown options located in `bitcoin.conf`, but they do fail is passed using the cli.

**Comment by sr-gi** [comment]
@svewa ca you give #284 a go? That should fix the option parser traceback you were getting. Turns out the option parsing logic was moved out of the try/catch in a previous commit and that case passed unnoticed.

**Comment by sr-gi** [comment]
Feel free to check #285 instead, which builds on top of #284 and also reports the unknown parameters from the config file to the logs.

**Comment by svewa** [comment]
On the nonexistent options, a warning is the minimum I'd expect. Other projects like apache, and honestly most software I know, just complains+exits. I wonder what the argument is to not exit, as it's obvious the software can't deliver what the user is expecting in this case.

I found a ton of issues/duplicates on bitcoind for this issue after you mentioned it - the only reasoning to not exit I found was that it's supposed to run with older configs, which might have deprecated parameters. So it runs, even if it possibly does not fulfill the users expectations. This is the stuff that limits email sending to 500 miles! (if https://web.mit.edu/jemorris/humor/500-miles is true) 

Will run #285 later. Thanks!

**Comment by sr-gi** [comment]
>I wonder what the argument is to not exit, as it's obvious the software can't deliver what the user is expecting in this case.

> This is the stuff that limits email sending to 500 miles! (if https://web.mit.edu/jemorris/humor/500-miles is true)

OK, you won me. I normally mimic `bitcoind`'s behaviour as much as possible so users that are used to Bitcoin Core find it easy to use, but I'd had to say your argument is really compelling, and the provided evidence is hilarious lol.

I'll rebase the PRs so it reports and exists.

**Comment by sr-gi** [comment]
@svewa I've repurposed #285 so it refuses to run instead of just reporting. I have applied the changes to all the "executables", i.e. `teosd`, `teos-cli` `teos-client` and the c-lightning plugin.

Let me know if you give it a go.

**Comment by sr-gi** [comment]
Hey @svewa did you have a chance to give it a go?

**Comment by svewa** [comment]
I like it much better like this. Testing I provided parameters without `-` or `--` like `teosd btcrpcuser=foo`, they didn't trigger an error. I would not bother :D

**Comment by sr-gi** [comment]
> I like it much better like this. Testing I provided parameters without `-` or `--` like `teosd btcrpcuser=foo`, they didn't trigger an error. I would not bother :D

Ohh, `teosd` does not expect arguments, only options, so args are ignored. I'll add a log about that, it's an easy fix.

**Comment by sr-gi** [comment]
https://github.com/talaia-labs/python-teos/blob/1f22438df1cc908d308872ba713f94a8fd523ec7/teos/teosd.py#L439-L443 This should have taken care of that. 

I've also changed the log message for wrong options to suggest running `teosd -h` instead of showing heal straight away, which seem more invasive and fill way more space on the terminal.

Before:
```
option --random not recognized. See teosd -h for a list of options.

USAGE:
	teosd [global options]

GLOBAL OPTIONS (all modifiable in conf file):
	--apibind 		Address that teos API will bind to. Defaults to 'localhost'.
	--apiport 		Port that teos API will bind to. Defaults to '9814'.
	--rpcbind 		Address that teos RPC server will bind to. Defaults to 'localhost'.
	--rpcport 		Port that teos RPC server will bind to. Defaults to '8814'.
	--btcnetwork 		Network bitcoind is connected to. Either mainnet, testnet or regtest. Defaults to 'mainnet'.
	--btcrpcuser 		bitcoind rpcuser. Defaults to 'user'.
	--btcrpcpassword 	bitcoind rpcpassword. Defaults to 'passwd'.
	--btcrpcconnect 	bitcoind rpcconnect. Defaults to 'localhost'.
	--btcrpcport 		bitcoind rpcport. Defaults to '8332'.
	--btcfeedconnect 	bitcoind zmq hostname (for blocks). Defaults to 'localhost'.
	--btcfeedport 		bitcoind zmq port (for blocks). Defaults to '28332'.
	--datadir 		Specify data directory. Defaults to '~\.teos'.
	--wsgi 			The WSGI server used to run the API. Either 'gunicorn' or 'waitress'. Defaults to 'gunicorn'.
	       			Notice 'gunicorn' does not work on Windows, so Windows users must use 'waitress'.
	-d, --daemon 		Run in background as a daemon.
	--overwritekey 		Overwrites the tower secret key. THIS IS IRREVERSIBLE AND WILL CHANGE YOUR TOWER ID.
	-h, --help 		Shows this message.
```

After:

```
option --random not recognized. See teosd -h for a list of options.
```
