### ISSUE TITLE
Watchtower is labelled misbehaving after first appointment

### ISSUE THREAD

**Issue by CMDRZOD** [talaia-labs/python-teos#312]
I've setup a watchtower on one PC and have another with my lightning node running with the watchtower plugin. I'm able to connect but end up with my watchtower being labelled misbehaving very quickly. Logs attached.

[API] Received register request  (from_addr=192.168.0.6)
Jun 09 17:30:55 kknd-sl teosd[124589]: 09/06/2022 17:30:55 [UsersDBM] Adding user to Gatekeeper's db  (user_id=033a71c55cf027b3053c114c6b8a2375a280a384676a24860922>Jun 09 17:30:55 kknd-sl teosd[124589]: 09/06/2022 17:30:55 [API] Sending response and disconnecting  (from_addr=192.168.0.6, response={'user_id': '033a71c55cf027b3>Jun 09 17:30:55 kknd-sl teosd[124589]: 09/06/2022 17:30:55 [API] 192.168.0.6 - - [09/Jun/2022:17:30:55 +0000] "POST /register HTTP/1.1" 200 346 "-" "python-request>Jun 09 17:32:08 kknd-sl teosd[124589]: 09/06/2022 17:32:08 [API] Received add_appointment request  (from_addr=192.168.0.6)
Jun 09 17:32:08 kknd-sl teosd[124589]: 09/06/2022 17:32:08 [UsersDBM] Adding user to Gatekeeper's db  (user_id=033a71c55cf027b3053c114c6b8a2375a280a384676a24860922>Jun 09 17:32:08 kknd-sl teosd[124589]: 09/06/2022 17:32:08 [AppointmentsDBM] Adding appointment to Watchers's db  (uuid=2d45c34a12d2940b9dca1bba8525f407da6b908e)
Jun 09 17:32:08 kknd-sl teosd[124589]: 09/06/2022 17:32:08 [Watcher] New appointment accepted  (locator=42f7399cf25a700fe1ea6bac3d8ed53d)
Jun 09 17:32:08 kknd-sl teosd[124589]: 09/06/2022 17:32:08 [API] Sending response and disconnecting  (from_addr=192.168.0.6, response={'locator': '42f7399cf25a700f>Jun 09 17:32:08 kknd-sl teosd[124589]: 09/06/2022 17:32:08 [API] 192.168.0.6 - - [09/Jun/2022:17:32:08 +0000] "POST /add_appointment HTTP/1.1" 200 238 "-" "python

{
   "id": "02f0958003c994e5c67db88d607668577b092e184dac09c072f918edf37d54e2e1",
   "netaddr": "http://192.168.0.1:9914",
   "available_slots": 298,
   "status": "misbehaving",
   "appointments": {},
   "pending_appointments": [],
   "invalid_appointments": [],
   "misbehaving_proof": {
      "appointment": {
         "locator": "42f7399cf25a700fe1ea6bac3d8ed53d",
         "encrypted_blob": "9c95f75cbc3e080661f31feae1d30f4f5761bade327217ad767430fbf77280d63973e285f2cf1ea8a31c3273300e66575135a706eb42fcdb9606d9cfbd9df3d472c712d8b01648cd022c9a391356b29d41527a95cccbf5223f0ed33271493c4212558e716ae57c3341eae1ff418d5078f3fdbfde51829ffc4646ead573f475ed2574a82f3959096bd4a53d11104460b5ee38b0cde1022d00e8b52d92067d7b8a83e492d07a5c03c67241a2b807ce86e552c611f8af7aa7fc08eea7ddda9b38ec69a85dc998c30d80763ffa8752f282e12450ee1428174f17ce00559fb3cfea7696955395738dae71f3c764de309f617a41bec928a2ea842ee7f0c24993",
         "to_self_delay": 20
      },
      "signature": "d9nswockotanj4ir6rf4aqrj1x4pxwpe7hjxgqtkzhet5pupqsq7w1g4btp14jc1u5fw1b3g5iq471zhzdneoe99um1xtoxukh11k3t7",
      "recovered_id": "02c4976bae4806d91be7e4fbd74927fd2be16ca599f902f9dacd8766f247e81df9",
      "receipt": "1fab112cf2badbaa8da615c020a7193b4b441c00be2f3759af9e2ff262fe43ffb735267568fda8a4d8e335af713b3f3784d9fd022597cb4fdeb5f4516f90d216ee000b4af1"
   }
}

Any idea why this is happening? Both PCs are running full BTC nodes.

Also another question, how can I make my watchtower reachable through tor? I tried messing with ports and addresses in the config file but couldn't make tor work.

**Comment by sr-gi** [comment]
Hi @CMDRZOD, `python-teos` is unofficially discontinued in favor of `rust-teos`.

In the next days I'll be releasing the rust watchtower-plugin for cln, so you'll be able to use the rust codebase for this. 

Notice that currently you may have issues if you try to use the the rust tower with the python client, given they are not fully compatible. I'd say just wait few a few days, or be reckless and [help us test it out pre-merge](https://github.com/talaia-labs/rust-teos/pull/58) 😄

**Comment by CMDRZOD** [comment]
Hi @sr-gi. I've got the rust version up and running complete with the plugin for core lightning. I've now got 2 towers setup, one remote and one local. They seem to be running well so far, CPU use is negligible. If there is any info you would like to be forwarded to you to help development please let me know. My main lightning node: https://1ml.com/node/02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a

Thank you for the great work. Where can I send you some lightning sats to help?

**Comment by sr-gi** [comment]
@CMDRZOD feel free to join slack and we can give a look at what's going on with that tor connection.

**Comment by sr-gi** [comment]
Regarding feedback, I'd say just use it for a while and let us know if anything weird happens, either related to UX or errors with the tower or the client. 

You giving us feedback is more than enough, but if you really want to send us some sats you can do so at either https://ln.bitcoinbeach.com/sr_gi or sr_gi@ln.bitcoinbeach.com

**Comment by CMDRZOD** [comment]
100k sats sent to you, sir. Will keep monitoring this github for new releases and using the watchtower on my node.
My node: https://1ml.com/node/02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a

**Comment by sr-gi** [comment]
Much appreciated. Do watch the `rust-teos` repo instead of this one though, since this will be discontinued.

**Comment by CMDRZOD** [comment]
Hi @sr-gi 

I have been using the plugin since we last spoke here. I have run into one issue where my watchtowers run out of appointments. When this happens I restarted the watchtower nodes and all has been well.

I also have found on my main lightning node when calling lightning-cli listtowers that this command can hang for a long time, sometimes up to 24 hours. I believe this is due to a watchtower appointments running out and the command hangs due to the amount of pending appoinments. Just my theory. 

I have also experienced a few c-lightning crashes but have not found any information that it is connected to the watchtower plugin. 

I'll be here refreshing this github daily waiting for the first release. Thank you.

**Comment by sr-gi** [comment]
> Hi @sr-gi
> 
> I have been using the plugin since we last spoke here. I have run into one issue where my watchtowers run out of appointments. When this happens I restarted the watchtower nodes and all has been well.

This should be normal behavior, but if the UX is not good we may want to change it, especially for altruistic towers. Once the user runs out of appointments it is supposed to re-register with the tower (`lightning-cli registertower ...`)

> I also have found on my main lightning node when calling lightning-cli listtowers that this command can hang for a long time, sometimes up to 24 hours. I believe this is due to a watchtower appointments running out and the command hangs due to the amount of pending appoinments. Just my theory.

Umm, interesting. We should limit the amount of appointment summaries kept in memory then, I'll look into this.

> I have also experienced a few c-lightning crashes but have not found any information that it is connected to the watchtower plugin.
> 
> I'll be here refreshing this github daily waiting for the first release. Thank you.
