### ISSUE TITLE
Decide an appropriate strategy for appointments with start block in the past

### ISSUE THREAD

**Issue by bigspider** [talaia-labs/python-teos#42]
The current code only accepts appointments that start in the future.

As the client might not be aware of the absolute latest block chain head (e.g. due to block propagation times), it could be convenient to accept appointments that start up to 1 or 2 blocks in the past (we are already doing that on pisa-eth).
Of course, this might mean checking a few past blocks when we get a new appointment.

**Comment by sr-gi** [comment]
Closed via #138
